name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Frontend ESLint
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend ESLint
        working-directory: ./frontend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # Backend ESLint
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend ESLint
        working-directory: ./backend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Frontend Prettier
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend Prettier
        working-directory: ./frontend
        run: npx prettier --check .

      # Backend Prettier
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend Prettier
        working-directory: ./backend
        run: npx prettier --check .
